export const allSubjects = [
    'História',
    'Política',
    'Economia',
    'Internet',
    'Softwares',
    'Tecnologia',
    'Ciência',
    'Matemática',
    'Física',
    'Química',
    'Medicina',
    'Biologia',
    'Geografia',
    'Outras línguas',
    'Ler poesias',
    'Escrever poesias',
    'Arte',
    'Religiões',
    'Dança',
    'Instrumentos musicais',
    'Teatro',
    'Filmes de terror',
    'Filmes de suspense',
    'Comédias',
    'Filmes românticos',
    'Filmes de guerra',
    'Filmes de ficção científica',
    'Carros',
    'Esportes',
    'Animais',
];
